@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJjYjA0ZDgxMjE2MTNkNzhiZWVkMTZmYWMiLCJuYW1lIjoiRGFuaWVsIFBpbGFudHJhIiwiZW1haWwiOiJkYW5pZWxwaWxhbnRyYUBtYWlsLmNvbSIsImF2YXRhciI6bnVsbCwiYWNjb3VudElkIjoiN2I2N2YwOGU1M2E1NDMyNTZlMWEzZjI1IiwiY3JlYXRlZEF0IjoiMjAyNS0wNC0xMFQxNzozMDoyNC42NjJaIiwiaWF0IjoxNzQ0MzA2MjQ4LCJleHAiOjE3NDQzOTI2NDh9.A_JtE483lnjh3DXPAOYmTfIKPPlDt61delKHvKmM20g

POST http://localhost:3005/api/purchase-list/add
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "title": "title6",
  "description": "anydescription",
  "products": [
    {
      "name": "Product 1",
      "quantity": 2,
      "unitPrice": 10,
      "totalPrice": 20
    }
  ]
}