POST http://localhost:3005/api/purchase-list/add
Content-Type: application/json

{
  "title": "anytitle",
  "description": "anydescription",
  "products": [
    {
      "name": "Product 1",
      "quantity": 2,
      "unitPrice": 10,
      "totalPrice": 20
    }
  ],
  "userId": "b8565741f66e14f7606aa551"
}