POST http://localhost:3005/api/signup
Content-Type: application/json

{
  "name": "Daniel Pilantra",
  "email": "danielpilantra@mail.com",
  "password": "password",
  "passwordConfirmation": "password"
}